name: XML Validation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ tooomm-actions_test ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libxml2-utils

      - name: Download XSD schema
        run: |
          wget https://raw.githubusercontent.com/Cockatrice/Cockatrice/master/doc/carddatabase_v3/cards.xsd -O carddb-v3.xsd
          wget https://raw.githubusercontent.com/Cockatrice/Cockatrice/master/doc/carddatabase_v4/cards.xsd -O carddb-v4.xsd

      - name: Validate XML files
        run: |
          xmllint --schema carddb-v3.xsd --noout challenge_tokens.xml
          xmllint --schema carddb-v4.xsd --noout tokens.xml
